spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/spring-test
    username: root
    password: ssw030422123!

jwt:
  secret: jwt
  accessExpiration: 36000000
  refreshExpiration: 864000000